## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Configuration for Alacritty, the GPU enhanced terminal emulator.
## It's a very basic and simple config file, for full configuration...
## See, /usr/share/doc/alacritty/example/alacritty.yml

## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/bspwm/alacritty/alacritty-colors.yml
  # - ~/.config/wal/templates/alacrittycolors.yml   ### New as of 16Mar23.  Used for Wal.
  - ~/.config/bspwm/alacritty/fonts.yml

      ## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.2'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 23

  padding:
    x: 6
    y: 6

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  #  history: 10000
  #multiplier: 3

## Background opacity
  opacity: 0.4

shell:
    program: /bin/tmux


## Cursor
cursor:
  style:
    shape: Block
    blinking: On
  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
#shell:
#  program: /bin/zsh
#  args:
#    - --login
