import = [
  "~/.config/bspwm/alacritty/fonts.toml",
  "~/.config/bspwm/alacritty/colors.toml"
]

live_config_reload = true

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.2"

[window]
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true
opacity = 0.4

  [window.dimensions]
  columns = 82
  lines = 23

  [window.padding]
  x = 6
  y = 6

[shell]
program = "/bin/tmux"

[cursor]
unfocused_hollow = false

  [cursor.style]
  shape = "Block"
  blinking = "On"

